use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'GWSecendDemo_Example' do
  pod 'GWSecendDemo', :path => '../'

  target 'GWSecendDemo_Tests' do
    inherit! :search_paths

    
  end
end
